apiVersion: v1
kind: Service
metadata:
  name: {{ include "keydb.fullname" . }}
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.keydb.port | int }}
      targetPort: keydb
      protocol: TCP
      name: server
  selector:
    {{- include "keydb.selectorLabels" . | nindent 4 }}
